version: "3"
services:
  app:
    container_name: flask
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
